name: Build and Upload Artifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-none-elf binutils-aarch64-none-elf


      - name: Run Makefile
        run: |
          
          cd demo-hello
          make TARGET_COMPILE=aarch64-none-elf-

      - name: Upload KPM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kpm-packages
          path: demo-hello/*.kpm
          if-no-files-found: error
